// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD5PaVP-WoNOGBODDwMX-EJXGBJCUytpRw',
    appId: '1:749082589403:web:0862925371ef5dc79334fe',
    messagingSenderId: '749082589403',
    projectId: 'tic-tac-toe-7fc87',
    authDomain: 'tic-tac-toe-7fc87.firebaseapp.com',
    storageBucket: 'tic-tac-toe-7fc87.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAjvJx38GI9sMhNvwTwcFXyvz9WEKkWwZc',
    appId: '1:749082589403:android:50b840873c5266339334fe',
    messagingSenderId: '749082589403',
    projectId: 'tic-tac-toe-7fc87',
    storageBucket: 'tic-tac-toe-7fc87.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC4W3Rh2AOqu-t4jgluGhcPJRlWnMmQuis',
    appId: '1:749082589403:ios:85bb391c3f36d6879334fe',
    messagingSenderId: '749082589403',
    projectId: 'tic-tac-toe-7fc87',
    storageBucket: 'tic-tac-toe-7fc87.appspot.com',
    iosBundleId: 'com.champ.ticTacToe',
  );
}
